cookie:
  expiry_days: 0
  key: cookiekey
  name: cookiename
credentials:
  usernames:
    griffin:
      avatar: "\U0001F9D1\U0001F3FC"
      failed_login_attempts: 0
      logged_in: true
      password: $2b$12$jId9COImjm/zSExdDDnIE.WP3sgShU2ozyPkvXjKkYUNhc3k4.JNi
      roles:
      - admin
      - editor
      - viewer
    siti:
      avatar: "\U0001F469\U0001F3FE"
      failed_login_attempts: 3
      logged_in: false
      password: $2b$12$Y7luI/JkZBo5wKytwYTaOu67tJ9MJeouYyER5RgYIVcKF7xPzkWAG
      roles:
      - editor
      - viewer
