cookie:
  expiry_days: 0
  key: cookiekey
  name: cookiename
credentials:
  usernames:
    griffin:
      failed_login_attempts: 3
      logged_in: false
      password: $2b$12$ntL3j0znAAtg1AVJzirgYeyI9M/e1Wcf71yFofM2/UB4oLpieZohK
      roles:
      - admin
      - editor
      - viewer
    siti:
      failed_login_attempts: 3
      logged_in: false
      password: $2b$12$zh.YPR0F5kasvQzGjzzJteDxqRu4M.zz0UqwdEzUpS3Nu6dpKhX8K
      roles:
      - editor
      - viewer
